version: 1.0.{build}
branches:
  only:
  - obs-vce-rebase
build:
  verbosity: minimal
environment:
  QTDIR: C:\Qt\5.6\msvc2015_64

install:
  - git submodule update --init --recursive
  - choco install -y curl
  - set PATH="C:\Program Files\7-Zip";%PATH%
  - curl -kLO https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-20160809-369ed11-win64-dev.zip
  - 7z x ffmpeg-20160809-369ed11-win64-dev.zip
  - set FFMPEG_PATH=%CD%\ffmpeg-20160809-369ed11-win64-dev.zip

