version: 1.0.{build}
branches:
  only:
  - obs-vce-rebase
configuration: Release
build:
  verbosity: minimal
  project: obs-studio.sln
environment:
  QTDIR: C:\Qt\5.6\msvc2015_64
platform: x64
artifacts:
- path: build
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake ../

install:
  - git submodule update --init --recursive
  - choco install -y curl
  - set PATH="C:\Program Files\7-Zip";%PATH%
  - curl -kLO https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-20160809-369ed11-win64-dev.zip
  - 7z x ffmpeg-20160809-369ed11-win64-dev.zip
  - set FFmpegPath=%CD%\ffmpeg-20160809-369ed11-win64-dev
  - curl -kLO https://curl.haxx.se/download/curl-7.50.1.zip
  - 7z x curl-7.50.1.zip
  - set curlPath=%CD%\curl-7.50.1
  - git clone http://git.videolan.org/git/x264.git
  - set x264Path=%CD%\x264

